class UserNotFoundError(Exception):
    pass


class UsernameAlreadyExistsError(Exception):
    pass
